version: '3.9'
services:
  thinnai-canary:
    image: 'thinnai-canary:latest'
    container_name: thinnai-canary
    ports:
      - '7022:6099'
    networks:
      - thinnai-network
    deploy:
      restart_policy: # Read this: https://docs.docker.com/compose/compose-file/deploy/#restart_policy
        condition: on-failure
        max_attempts: 3
        window: 120s
networks:
  thinnai-network:
    driver: bridge
    external: true
