version: '3.9'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '25000:27017'
    volumes:
      - /usr/local/data/mongodb:/data/db
    networks:
      - thinnai-network

networks:
  thinnai-network:
    driver: bridge
