export enum ROUTES {
  FORGOT = '/forgot',
  ROOT = '/',
  HOST_LANDING = '/host',
  POLICY_BASE = '/policy',
  INFO = '/info',
  LOGIN = '/login',
  ONBOARD = '/onboard',
  GUEST_REGISTRATION = '/registration',
  GUEST_MANAGE_PROFILE = '/manage',
  EXPLORE = '/explore',
  PROPERTY_DETAIL = '/thinnai',
  CHAT = '/chat',
  BOOKING_TRACKER = '/track',
  ONGOING = '/track/ongoing',
  ENQUIRY = '/track/enquiry',
  REQUESTS = '/track/requests',
  CONFIRMED = '/track/confirmed',
  CANCELLED = '/track/cancelled',
  COMPLETED = '/track/completed',
  INVITED_TO = '/track/invited',
  ENQUIRY_STATUS = '/track/enquiry/status',
  EDIT='/track/confirmed/edit',
  CONFIRM_INVITATION = '/confirm',
  PAYMENT = '/payment',
  PAYMENTCC = '/paybycc',
  CONGRATULATIONS = '/congratulations',
  PAYMENT_STATUS = '/payment-status',
  PAYMENT_CANCELLED = '/payment-cancelled',
  PROFILE = '/profile',
  PERSONAL_INFO = '/profile/personal-info',
  MY_REVIEWS = '/profile/my-reviews',
  FRIEND_LIST = '/profile/friend-list',
  PAYMENTS_REQUESTS = 'profile/payments-requests',
  PAYMENTS = 'profile/payments-requests/payments',
  PRIVACY_SHARING = '/profile/privacy-sharing',
  SHARING = '/profile/privacy-sharing/sharing',
  SERVICES = '/profile/privacy-sharing/services',
  ENQUIRY_SUMMARY = '/enquiry-summary',
  RESET_PASSWORD='/reset-password',
  UNPAID='/track/unpaid'
}

export enum BOOKING_VIEW_TYPE {
  EDIT = 'edit',
  RESCHEDULE = 'reschedule',
  DETAILS = 'details',
}
